
function Controller_module_config(this_block)

  % Revision History:
  %
  %   04-Jan-2020  (12:30 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     C:\MyDocs\University\FPGA\Radar_project\Radar_project.srcs\sources_1\new\Controller_module.vhd
  %
  %

  this_block.setTopLevelLanguage('VHDL');

  this_block.setEntityName('Controller_module');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  %this_block.tagAsCombinational;

  this_block.addSimulinkInport('start');
  this_block.addSimulinkInport('stop');
  this_block.addSimulinkInport('reset');
  this_block.addSimulinkInport('end_pwm');
  this_block.addSimulinkInport('end_sharp');
  this_block.addSimulinkInport('end_adc');

  this_block.addSimulinkOutport('start_pwm');
  this_block.addSimulinkOutport('start_sharp');
  this_block.addSimulinkOutport('start_adc');
  this_block.addSimulinkOutport('change_h');
  this_block.addSimulinkOutport('data_rdy');

  start_pwm_port = this_block.port('start_pwm');
  start_pwm_port.setType('UFix_1_0');
  start_pwm_port.useHDLVector(false);
  start_sharp_port = this_block.port('start_sharp');
  start_sharp_port.setType('UFix_1_0');
  start_sharp_port.useHDLVector(false);
  start_adc_port = this_block.port('start_adc');
  start_adc_port.setType('UFix_1_0');
  start_adc_port.useHDLVector(false);
  change_h_port = this_block.port('change_h');
  change_h_port.setType('UFix_1_0');
  change_h_port.useHDLVector(false);
  data_rdy_port = this_block.port('data_rdy');
  data_rdy_port.setType('UFix_1_0');
  data_rdy_port.useHDLVector(false);

  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('start').width ~= 1);
      this_block.setError('Input data type for port "start" must have width=1.');
    end

    this_block.port('start').useHDLVector(false);

    if (this_block.port('stop').width ~= 1);
      this_block.setError('Input data type for port "stop" must have width=1.');
    end

    this_block.port('stop').useHDLVector(false);

    if (this_block.port('reset').width ~= 1);
      this_block.setError('Input data type for port "reset" must have width=1.');
    end

    this_block.port('reset').useHDLVector(false);

    if (this_block.port('end_pwm').width ~= 1);
      this_block.setError('Input data type for port "end_pwm" must have width=1.');
    end

    this_block.port('end_pwm').useHDLVector(false);

    if (this_block.port('end_sharp').width ~= 1);
      this_block.setError('Input data type for port "end_sharp" must have width=1.');
    end

    this_block.port('end_sharp').useHDLVector(false);

    if (this_block.port('end_adc').width ~= 1);
      this_block.setError('Input data type for port "end_adc" must have width=1.');
    end

    this_block.port('end_adc').useHDLVector(false);

  end  % if(inputTypesKnown)
  % -----------------------------

  % -----------------------------
   if (this_block.inputRatesKnown)
     setup_as_single_rate(this_block,'src_clk','src_ce')
   end  % if(inputRatesKnown)
  % -----------------------------

    uniqueInputRates = unique(this_block.getInputRates);


  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  this_block.addFile('../Radar_project/Radar_project.srcs/sources_1/new/Controller_module.vhd');

return;


% ------------------------------------------------------------

function setup_as_single_rate(block,clkname,cename) 
  inputRates = block.inputRates; 
  uniqueInputRates = unique(inputRates); 
  if (length(uniqueInputRates)==1 & uniqueInputRates(1)==Inf) 
    block.addError('The inputs to this block cannot all be constant.'); 
    return; 
  end 
  if (uniqueInputRates(end) == Inf) 
     hasConstantInput = true; 
     uniqueInputRates = uniqueInputRates(1:end-1); 
  end 
  if (length(uniqueInputRates) ~= 1) 
    block.addError('The inputs to this block must run at a single rate.'); 
    return; 
  end 
  theInputRate = uniqueInputRates(1); 
  for i = 1:block.numSimulinkOutports 
     block.outport(i).setRate(theInputRate); 
  end 
  block.addClkCEPair(clkname,cename,theInputRate); 
  return; 

% ------------------------------------------------------------

